import { VendorDefinition } from "./types";

export const VENDORS: VendorDefinition[] = [
  // ─── AI / LLM ────────────────────────────────────────────────────────────────
  {
    id: "openai",
    name: "OpenAI",
    category: "ai",
    domains: ["api.openai.com"],
    envVars: ["OPENAI_API_KEY"],
    importHints: ["openai", "OpenAI", "from 'openai'", "from \"openai\""],
    dependencyHints: ["openai"],
    apiKeyPatterns: ["sk-proj-", "sk-"],
    pricingModel: "per_token",
    planDiscovery: { canOAuth: false, notes: "Requires billing export or usage API key." },
    cheaperAlternativeHeadline: "GPT-4 class models often have cheaper alternatives for classification/extraction tasks.",
    alternatives: [
      { vendorId: "groq", rationale: "Near-zero latency inference on open models, drastically cheaper for high-throughput.", estimatedSavingsPct: 60 },
      { vendorId: "mistral", rationale: "Open-weight models via API, significantly cheaper per token.", estimatedSavingsPct: 50 },
      { vendorId: "anthropic", rationale: "Claude models competitive for many text tasks.", estimatedSavingsPct: 5 },
      { vendorId: "aws-bedrock", rationale: "Centralize multi-model access, governance, and cost.", estimatedSavingsPct: 10 },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    category: "ai",
    domains: ["api.anthropic.com"],
    envVars: ["ANTHROPIC_API_KEY"],
    importHints: ["@anthropic-ai/sdk", "Anthropic", "from '@anthropic-ai/sdk'"],
    dependencyHints: ["@anthropic-ai/sdk"],
    apiKeyPatterns: ["sk-ant-"],
    pricingModel: "per_token",
    planDiscovery: { canOAuth: false, notes: "Billing access is account-scoped via console." },
    cheaperAlternativeHeadline: "Claude Haiku is competitive on cost for simpler tasks.",
    alternatives: [
      { vendorId: "openai", rationale: "GPT-4o mini is cheaper for simple classification.", estimatedSavingsPct: 10 },
      { vendorId: "groq", rationale: "Llama 3 on Groq for high-throughput low-latency use cases.", estimatedSavingsPct: 55 },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    category: "ai",
    domains: ["api.groq.com"],
    envVars: ["GROQ_API_KEY"],
    importHints: ["groq", "from 'groq'", "Groq"],
    dependencyHints: ["groq"],
    apiKeyPatterns: ["gsk_"],
    pricingModel: "per_token",
    planDiscovery: { canOAuth: false, notes: "Usage tracked via console." },
    alternatives: [
      { vendorId: "openai", rationale: "GPT-4 class models if quality ceiling is needed." },
    ],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    category: "ai",
    domains: ["api.mistral.ai"],
    envVars: ["MISTRAL_API_KEY"],
    importHints: ["@mistralai/mistralai", "mistralai", "MistralClient"],
    dependencyHints: ["@mistralai/mistralai"],
    apiKeyPatterns: [],
    pricingModel: "per_token",
    planDiscovery: { canOAuth: false, notes: "Billing via console." },
    alternatives: [
      { vendorId: "groq", rationale: "Even faster inference for Mistral models via Groq.", estimatedSavingsPct: 30 },
    ],
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "ai",
    domains: ["api.cohere.ai", "api.cohere.com"],
    envVars: ["COHERE_API_KEY"],
    importHints: ["cohere", "CohereClient", "from 'cohere-ai'"],
    dependencyHints: ["cohere-ai", "cohere"],
    apiKeyPatterns: [],
    pricingModel: "per_token",
    planDiscovery: { canOAuth: false, notes: "Usage API available for enterprise accounts." },
    alternatives: [
      { vendorId: "openai", rationale: "Embeddings and reranking available from OpenAI too.", estimatedSavingsPct: 10 },
    ],
  },
  {
    id: "replicate",
    name: "Replicate",
    category: "ai",
    domains: ["api.replicate.com"],
    envVars: ["REPLICATE_API_TOKEN"],
    importHints: ["replicate", "from 'replicate'"],
    dependencyHints: ["replicate"],
    apiKeyPatterns: ["r8_"],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Billing via console." },
    alternatives: [
      { vendorId: "aws-bedrock", rationale: "Self-host models via Bedrock for predictable pricing.", estimatedSavingsPct: 25 },
    ],
  },
  {
    id: "aws-bedrock",
    name: "AWS Bedrock",
    category: "ai",
    domains: ["bedrock-runtime", "bedrock.us-east-1.amazonaws.com", "amazonaws.com"],
    envVars: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"],
    importHints: ["@aws-sdk/client-bedrock-runtime", "BedrockRuntimeClient", "BedrockClient"],
    dependencyHints: ["@aws-sdk/client-bedrock-runtime", "@aws-sdk/client-bedrock"],
    apiKeyPatterns: [],
    pricingModel: "per_token",
    planDiscovery: { canOAuth: true, notes: "AWS Cost Explorer API available with IAM permissions." },
    alternatives: [
      { vendorId: "openai", rationale: "Direct model provider for simpler setups.", estimatedSavingsPct: 5 },
    ],
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "ai",
    domains: ["api.elevenlabs.io"],
    envVars: ["ELEVENLABS_API_KEY", "XI_API_KEY"],
    importHints: ["elevenlabs", "ElevenLabs", "from 'elevenlabs'"],
    dependencyHints: ["elevenlabs"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Usage via console." },
    alternatives: [
      { vendorId: "assemblyai", rationale: "AssemblyAI covers STT cheaper.", estimatedSavingsPct: 20 },
    ],
  },
  {
    id: "assemblyai",
    name: "AssemblyAI",
    category: "ai",
    domains: ["api.assemblyai.com"],
    envVars: ["ASSEMBLYAI_API_KEY"],
    importHints: ["assemblyai", "AssemblyAI", "from 'assemblyai'"],
    dependencyHints: ["assemblyai"],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Usage API available." },
    alternatives: [
      { vendorId: "deepgram", rationale: "Deepgram is often cheaper for transcription at scale.", estimatedSavingsPct: 30 },
    ],
  },
  {
    id: "deepgram",
    name: "Deepgram",
    category: "ai",
    domains: ["api.deepgram.com"],
    envVars: ["DEEPGRAM_API_KEY"],
    importHints: ["@deepgram/sdk", "Deepgram", "createClient"],
    dependencyHints: ["@deepgram/sdk"],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Usage via console." },
    alternatives: [
      { vendorId: "assemblyai", rationale: "AssemblyAI for more features (sentiment, chapters).", estimatedSavingsPct: 10 },
    ],
  },
  {
    id: "pinecone",
    name: "Pinecone",
    category: "ai",
    domains: ["controller.us-east1-gcp.pinecone.io", "pinecone.io", "api.pinecone.io"],
    envVars: ["PINECONE_API_KEY", "PINECONE_ENVIRONMENT"],
    importHints: ["@pinecone-database/pinecone", "PineconeClient", "Pinecone"],
    dependencyHints: ["@pinecone-database/pinecone", "pinecone-client"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Billing via console." },
    alternatives: [
      { vendorId: "supabase", rationale: "Supabase pgvector for simpler vector search at lower cost.", estimatedSavingsPct: 40 },
    ],
  },

  // ─── Payments ────────────────────────────────────────────────────────────────
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    domains: ["api.stripe.com", "js.stripe.com"],
    envVars: ["STRIPE_SECRET_KEY", "STRIPE_PUBLISHABLE_KEY", "STRIPE_WEBHOOK_SECRET"],
    importHints: ["stripe", "Stripe", "@stripe/stripe-js", "@stripe/react-stripe-js"],
    dependencyHints: ["stripe", "@stripe/stripe-js", "@stripe/react-stripe-js"],
    apiKeyPatterns: ["sk_live_", "pk_live_", "sk_test_", "pk_test_"],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: true, notes: "OAuth Connect for merchant metadata access is well-supported." },
    cheaperAlternativeHeadline: "Alternative processors may reduce fees at higher volumes.",
    alternatives: [
      { vendorId: "paddle", rationale: "Merchant of record model simplifies tax compliance.", estimatedSavingsPct: 5 },
    ],
  },
  {
    id: "plaid",
    name: "Plaid",
    category: "payments",
    domains: ["production.plaid.com", "sandbox.plaid.com", "plaid.com"],
    envVars: ["PLAID_CLIENT_ID", "PLAID_SECRET", "PLAID_ENV"],
    importHints: ["plaid", "PlaidApi", "Configuration"],
    dependencyHints: ["plaid"],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Billing via Plaid dashboard." },
    alternatives: [
      { vendorId: "stripe", rationale: "Stripe Financial Connections for bank account linking.", estimatedSavingsPct: 20 },
    ],
  },

  // ─── SMS / Voice ─────────────────────────────────────────────────────────────
  {
    id: "twilio",
    name: "Twilio",
    category: "sms",
    domains: ["api.twilio.com", "notify.twilio.com"],
    envVars: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_PHONE_NUMBER"],
    importHints: ["twilio", "Twilio"],
    dependencyHints: ["twilio"],
    apiKeyPatterns: ["SK", "AC"],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Usage APIs available with account credentials." },
    cheaperAlternativeHeadline: "SMS costs vary significantly by region and carrier.",
    alternatives: [
      { vendorId: "vonage", rationale: "Vonage (Nexmo) is often cheaper for international SMS.", estimatedSavingsPct: 20 },
    ],
  },
  {
    id: "vonage",
    name: "Vonage",
    category: "sms",
    domains: ["api.nexmo.com", "api.vonage.com", "rest.nexmo.com"],
    envVars: ["VONAGE_API_KEY", "VONAGE_API_SECRET", "NEXMO_API_KEY", "NEXMO_API_SECRET"],
    importHints: ["@vonage/server-sdk", "Vonage", "Nexmo"],
    dependencyHints: ["@vonage/server-sdk", "nexmo"],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Usage via console." },
    alternatives: [
      { vendorId: "twilio", rationale: "Twilio for better developer experience in North America.", estimatedSavingsPct: 5 },
    ],
  },

  // ─── Email ────────────────────────────────────────────────────────────────────
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "email",
    domains: ["api.sendgrid.com", "sendgrid.com"],
    envVars: ["SENDGRID_API_KEY"],
    importHints: ["@sendgrid/mail", "@sendgrid/client", "sendgrid"],
    dependencyHints: ["@sendgrid/mail", "@sendgrid/client"],
    apiKeyPatterns: ["SG."],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Billing connection depends on account permissions." },
    cheaperAlternativeHeadline: "Email tools vary widely in per-email cost at different volume tiers.",
    alternatives: [
      { vendorId: "resend", rationale: "Modern developer experience, typically cheaper at lower volumes.", estimatedSavingsPct: 30 },
      { vendorId: "mailgun", rationale: "Pay-as-you-go pricing often cheaper than subscription tiers.", estimatedSavingsPct: 20 },
      { vendorId: "postmark", rationale: "Best transactional deliverability, similar pricing.", estimatedSavingsPct: 10 },
    ],
  },
  {
    id: "resend",
    name: "Resend",
    category: "email",
    domains: ["api.resend.com"],
    envVars: ["RESEND_API_KEY"],
    importHints: ["resend", "Resend", "from 'resend'"],
    dependencyHints: ["resend"],
    apiKeyPatterns: ["re_"],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Usage via console." },
    alternatives: [
      { vendorId: "postmark", rationale: "Postmark for highest transactional deliverability.", estimatedSavingsPct: 5 },
    ],
  },
  {
    id: "mailgun",
    name: "Mailgun",
    category: "email",
    domains: ["api.mailgun.net", "api.eu.mailgun.net"],
    envVars: ["MAILGUN_API_KEY", "MAILGUN_DOMAIN"],
    importHints: ["mailgun.js", "Mailgun", "formData"],
    dependencyHints: ["mailgun.js", "form-data"],
    apiKeyPatterns: ["key-"],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Usage API available." },
    alternatives: [
      { vendorId: "resend", rationale: "Better developer ergonomics for React email.", estimatedSavingsPct: 10 },
    ],
  },
  {
    id: "postmark",
    name: "Postmark",
    category: "email",
    domains: ["api.postmarkapp.com"],
    envVars: ["POSTMARK_API_TOKEN", "POSTMARK_SERVER_TOKEN"],
    importHints: ["postmark", "ServerClient"],
    dependencyHints: ["postmark"],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Usage via console." },
    alternatives: [
      { vendorId: "resend", rationale: "Resend for simpler React-based email templates.", estimatedSavingsPct: 15 },
    ],
  },

  // ─── Auth ─────────────────────────────────────────────────────────────────────
  {
    id: "auth0",
    name: "Auth0",
    category: "auth",
    domains: ["auth0.com", ".auth0.com"],
    envVars: ["AUTH0_SECRET", "AUTH0_BASE_URL", "AUTH0_ISSUER_BASE_URL", "AUTH0_CLIENT_ID", "AUTH0_CLIENT_SECRET"],
    importHints: ["@auth0/nextjs-auth0", "auth0", "Auth0Client"],
    dependencyHints: ["@auth0/nextjs-auth0", "auth0"],
    apiKeyPatterns: [],
    pricingModel: "seat_based",
    planDiscovery: { canOAuth: true, notes: "Management API allows querying MAU and billing data." },
    cheaperAlternativeHeadline: "Auth0 pricing scales steeply with MAU.",
    alternatives: [
      { vendorId: "clerk", rationale: "Developer-first, often cheaper at moderate MAU.", estimatedSavingsPct: 20 },
      { vendorId: "supabase", rationale: "Built-in auth with generous free tier.", estimatedSavingsPct: 40 },
    ],
  },
  {
    id: "clerk",
    name: "Clerk",
    category: "auth",
    domains: ["api.clerk.com", "clerk.dev", "clerk.com"],
    envVars: ["CLERK_SECRET_KEY", "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", "CLERK_PUBLISHABLE_KEY"],
    importHints: ["@clerk/nextjs", "@clerk/clerk-sdk-node", "ClerkProvider"],
    dependencyHints: ["@clerk/nextjs", "@clerk/clerk-sdk-node"],
    apiKeyPatterns: ["sk_live_", "sk_test_"],
    pricingModel: "seat_based",
    planDiscovery: { canOAuth: false, notes: "Usage via console; backend API available." },
    alternatives: [
      { vendorId: "auth0", rationale: "Auth0 for enterprise compliance requirements.", estimatedSavingsPct: 5 },
      { vendorId: "supabase", rationale: "Supabase auth for simple cases at lower cost.", estimatedSavingsPct: 35 },
    ],
  },

  // ─── Cloud / Hosting ─────────────────────────────────────────────────────────
  {
    id: "vercel",
    name: "Vercel",
    category: "cloud",
    domains: ["vercel.com", "api.vercel.com"],
    envVars: ["VERCEL_TOKEN", "VERCEL_PROJECT_ID", "VERCEL_ORG_ID"],
    importHints: ["@vercel/analytics", "@vercel/speed-insights", "Analytics"],
    dependencyHints: ["@vercel/analytics", "@vercel/speed-insights", "@vercel/og"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: true, notes: "Vercel REST API exposes team and deployment data." },
    cheaperAlternativeHeadline: "Bandwidth and function invocations scale with traffic.",
    alternatives: [
      { vendorId: "cloudflare", rationale: "Cloudflare Workers + Pages for significantly cheaper at scale.", estimatedSavingsPct: 40 },
    ],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "cdn",
    domains: ["api.cloudflare.com", "cloudflare.com"],
    envVars: ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID", "CF_PAGES_TOKEN"],
    importHints: ["cloudflare", "Cloudflare", "@cloudflare/workers-types"],
    dependencyHints: ["wrangler", "@cloudflare/workers-types", "miniflare"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: true, notes: "Cloudflare API provides usage and billing data." },
    alternatives: [
      { vendorId: "vercel", rationale: "Vercel for better Next.js integration.", estimatedSavingsPct: 10 },
    ],
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "cloud",
    domains: ["supabase.com", ".supabase.co", "supabase.io"],
    envVars: ["SUPABASE_URL", "SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY", "NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"],
    importHints: ["@supabase/supabase-js", "createClient", "@supabase/ssr"],
    dependencyHints: ["@supabase/supabase-js", "@supabase/ssr"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: true, notes: "Management API available for billing and usage data." },
    alternatives: [
      { vendorId: "neon", rationale: "Neon for pure serverless Postgres at lower cost.", estimatedSavingsPct: 20 },
    ],
  },
  {
    id: "neon",
    name: "Neon",
    category: "cloud",
    domains: ["neon.tech", ".neon.tech"],
    envVars: ["DATABASE_URL", "NEON_DATABASE_URL"],
    importHints: ["@neondatabase/serverless", "neon"],
    dependencyHints: ["@neondatabase/serverless"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "API available; usage in console." },
    alternatives: [
      { vendorId: "supabase", rationale: "Supabase adds auth, storage, and realtime on top of Postgres.", estimatedSavingsPct: 5 },
    ],
  },
  {
    id: "upstash",
    name: "Upstash (Redis)",
    category: "cloud",
    domains: ["upstash.io", ".upstash.io"],
    envVars: ["UPSTASH_REDIS_REST_URL", "UPSTASH_REDIS_REST_TOKEN", "KV_REST_API_URL", "KV_REST_API_TOKEN"],
    importHints: ["@upstash/redis", "@upstash/ratelimit", "Redis"],
    dependencyHints: ["@upstash/redis", "@upstash/ratelimit", "@upstash/qstash"],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "REST API for usage data." },
    alternatives: [
      { vendorId: "cloudflare", rationale: "Cloudflare KV for key-value at lower cost.", estimatedSavingsPct: 30 },
    ],
  },

  // ─── Monitoring / Observability ───────────────────────────────────────────────
  {
    id: "datadog",
    name: "Datadog",
    category: "monitoring",
    domains: ["api.datadoghq.com", "datadoghq.com"],
    envVars: ["DD_API_KEY", "DD_APP_KEY", "DATADOG_API_KEY"],
    importHints: ["dd-trace", "datadog", "StatsD"],
    dependencyHints: ["dd-trace", "datadog", "hot-shots"],
    apiKeyPatterns: [],
    pricingModel: "seat_based",
    planDiscovery: { canOAuth: true, notes: "Usage API available with app key for billing data." },
    cheaperAlternativeHeadline: "Observability tools vary 5-10x in per-host pricing.",
    alternatives: [
      { vendorId: "sentry", rationale: "Sentry covers error tracking at much lower cost.", estimatedSavingsPct: 60 },
    ],
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "monitoring",
    domains: ["sentry.io", "o0.ingest.sentry.io", ".ingest.sentry.io"],
    envVars: ["SENTRY_DSN", "SENTRY_AUTH_TOKEN", "NEXT_PUBLIC_SENTRY_DSN"],
    importHints: ["@sentry/nextjs", "@sentry/node", "@sentry/react", "Sentry"],
    dependencyHints: ["@sentry/nextjs", "@sentry/node", "@sentry/react"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: true, notes: "REST API for project and billing data." },
    alternatives: [
      { vendorId: "datadog", rationale: "Datadog for full APM and infrastructure monitoring.", estimatedSavingsPct: 10 },
    ],
  },

  // ─── Analytics ───────────────────────────────────────────────────────────────
  {
    id: "segment",
    name: "Segment",
    category: "other",
    domains: ["api.segment.io", "cdn.segment.com"],
    envVars: ["SEGMENT_WRITE_KEY", "NEXT_PUBLIC_SEGMENT_WRITE_KEY"],
    importHints: ["@segment/analytics-next", "Analytics", "AnalyticsBrowser"],
    dependencyHints: ["@segment/analytics-next", "analytics"],
    apiKeyPatterns: [],
    pricingModel: "seat_based",
    planDiscovery: { canOAuth: false, notes: "Usage via console; limited billing API." },
    cheaperAlternativeHeadline: "Segment pricing grows steeply with MTU.",
    alternatives: [
      { vendorId: "mixpanel", rationale: "Mixpanel at lower MTU cost.", estimatedSavingsPct: 30 },
    ],
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    category: "other",
    domains: ["api.mixpanel.com", "data.mixpanel.com"],
    envVars: ["MIXPANEL_TOKEN", "NEXT_PUBLIC_MIXPANEL_TOKEN"],
    importHints: ["mixpanel", "mixpanel-browser", "Mixpanel"],
    dependencyHints: ["mixpanel", "mixpanel-browser"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Usage via console." },
    alternatives: [
      { vendorId: "segment", rationale: "Segment for multi-destination event routing.", estimatedSavingsPct: 10 },
    ],
  },

  // ─── Search ───────────────────────────────────────────────────────────────────
  {
    id: "algolia",
    name: "Algolia",
    category: "search",
    domains: ["algolia.net", "algolia.io", "algolianet.com"],
    envVars: ["ALGOLIA_APP_ID", "ALGOLIA_API_KEY", "ALGOLIA_SEARCH_API_KEY", "NEXT_PUBLIC_ALGOLIA_APP_ID"],
    importHints: ["algoliasearch", "instantsearch", "react-instantsearch"],
    dependencyHints: ["algoliasearch", "react-instantsearch", "@algolia/client-search"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Usage API via console or search analytics API." },
    cheaperAlternativeHeadline: "Search costs scale with records and operations.",
    alternatives: [
      { vendorId: "supabase", rationale: "Supabase full-text search for simpler use cases at no extra cost.", estimatedSavingsPct: 50 },
    ],
  },

  // ─── Maps ─────────────────────────────────────────────────────────────────────
  {
    id: "google-maps",
    name: "Google Maps",
    category: "other",
    domains: ["maps.googleapis.com", "maps.google.com"],
    envVars: ["GOOGLE_MAPS_API_KEY", "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY"],
    importHints: ["@googlemaps/js-api-loader", "google.maps", "@react-google-maps/api"],
    dependencyHints: ["@googlemaps/js-api-loader", "@react-google-maps/api"],
    apiKeyPatterns: ["AIza"],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: true, notes: "Google Cloud billing API available." },
    alternatives: [
      { vendorId: "mapbox", rationale: "Mapbox is often cheaper for custom-styled maps.", estimatedSavingsPct: 25 },
    ],
  },
  {
    id: "mapbox",
    name: "Mapbox",
    category: "other",
    domains: ["api.mapbox.com", "events.mapbox.com"],
    envVars: ["MAPBOX_ACCESS_TOKEN", "NEXT_PUBLIC_MAPBOX_TOKEN"],
    importHints: ["mapbox-gl", "react-map-gl", "mapboxgl"],
    dependencyHints: ["mapbox-gl", "react-map-gl"],
    apiKeyPatterns: ["pk.eyJ"],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Usage in console." },
    alternatives: [
      { vendorId: "google-maps", rationale: "Google Maps for broader geocoding coverage.", estimatedSavingsPct: 10 },
    ],
  },

  // ─── Cloud Infrastructure ─────────────────────────────────────────────────
  {
    id: "aws",
    name: "AWS",
    category: "cloud",
    domains: ["amazonaws.com", "aws.amazon.com", "s3.amazonaws.com", "lambda.amazonaws.com"],
    envVars: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION", "AWS_DEFAULT_REGION"],
    importHints: ["@aws-sdk", "aws-sdk", "from '@aws-sdk/", "AmazonWebServices"],
    dependencyHints: ["@aws-sdk/client-s3", "@aws-sdk/client-lambda", "@aws-sdk/client-dynamodb", "aws-sdk"],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: true, notes: "AWS Cost Explorer API available with IAM cost:* permissions." },
    alternatives: [
      { vendorId: "gcp", rationale: "GCP often cheaper for compute-heavy workloads.", estimatedSavingsPct: 10 },
      { vendorId: "cloudflare", rationale: "Cloudflare Workers/R2 drastically cheaper for edge + storage.", estimatedSavingsPct: 40 },
    ],
  },
  {
    id: "gcp",
    name: "Google Cloud",
    category: "cloud",
    domains: ["googleapis.com", "storage.googleapis.com", "cloudfunctions.googleapis.com"],
    envVars: ["GOOGLE_APPLICATION_CREDENTIALS", "GOOGLE_CLOUD_PROJECT", "GCP_PROJECT_ID"],
    importHints: ["@google-cloud", "googleapis", "google-auth-library"],
    dependencyHints: ["@google-cloud/storage", "@google-cloud/functions-framework", "googleapis"],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: true, notes: "Cloud Billing API available via OAuth." },
    alternatives: [
      { vendorId: "aws", rationale: "AWS for broader service ecosystem.", estimatedSavingsPct: 5 },
      { vendorId: "cloudflare", rationale: "Cloudflare Workers for serverless at much lower cost.", estimatedSavingsPct: 50 },
    ],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "cdn",
    domains: ["api.cloudflare.com", "cloudflare.com", "workers.dev"],
    envVars: ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID", "CF_API_TOKEN"],
    importHints: ["cloudflare", "@cloudflare/workers-types", "wrangler"],
    dependencyHints: ["wrangler", "@cloudflare/workers-types", "cloudflare"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Billing via dashboard API." },
    alternatives: [
      { vendorId: "aws", rationale: "AWS CloudFront for enterprise CDN needs.", estimatedSavingsPct: 5 },
    ],
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "cloud",
    domains: ["vercel.com", "api.vercel.com", "vercel.app"],
    envVars: ["VERCEL_TOKEN", "VERCEL_ORG_ID", "VERCEL_PROJECT_ID"],
    importHints: ["@vercel/", "vercel"],
    dependencyHints: ["@vercel/analytics", "@vercel/speed-insights", "@vercel/og"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: true, notes: "Vercel OAuth integration available via Marketplace." },
    alternatives: [
      { vendorId: "cloudflare", rationale: "Cloudflare Pages has a very generous free tier.", estimatedSavingsPct: 60 },
    ],
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "cloud",
    domains: ["supabase.co", "supabase.io", "supabase.com"],
    envVars: ["SUPABASE_URL", "SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY", "NEXT_PUBLIC_SUPABASE_URL"],
    importHints: ["@supabase/supabase-js", "createClient", "supabase"],
    dependencyHints: ["@supabase/supabase-js", "@supabase/ssr", "@supabase/auth-helpers-nextjs"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Management API available with service role key." },
    alternatives: [
      { vendorId: "neon", rationale: "Neon for serverless Postgres at lower cost if not using Supabase auth/storage.", estimatedSavingsPct: 30 },
      { vendorId: "planetscale", rationale: "PlanetScale for MySQL-compatible serverless DB.", estimatedSavingsPct: 20 },
    ],
  },
  {
    id: "neon",
    name: "Neon",
    category: "cloud",
    domains: ["neon.tech", "neondb.com"],
    envVars: ["DATABASE_URL", "NEON_DATABASE_URL"],
    importHints: ["@neondatabase/serverless", "neon"],
    dependencyHints: ["@neondatabase/serverless"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Usage API available via Neon API key." },
    alternatives: [
      { vendorId: "supabase", rationale: "Supabase includes auth and storage if you need more than just DB.", estimatedSavingsPct: 0 },
    ],
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    category: "cloud",
    domains: ["planetscale.com", "aws.connect.psdb.cloud"],
    envVars: ["DATABASE_URL", "PLANETSCALE_SERVICE_TOKEN", "PSCALE_TOKEN"],
    importHints: ["@planetscale/database", "planetscale"],
    dependencyHints: ["@planetscale/database"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Billing via dashboard." },
    alternatives: [
      { vendorId: "neon", rationale: "Neon for Postgres-compatible serverless DB.", estimatedSavingsPct: 20 },
    ],
  },
  {
    id: "railway",
    name: "Railway",
    category: "cloud",
    domains: ["railway.app", "up.railway.app"],
    envVars: ["RAILWAY_TOKEN", "RAILWAY_API_KEY"],
    importHints: [],
    dependencyHints: [],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Usage tracked via Railway dashboard." },
    alternatives: [
      { vendorId: "cloudflare", rationale: "Cloudflare Workers for stateless services at lower cost.", estimatedSavingsPct: 50 },
      { vendorId: "vercel", rationale: "Vercel for Next.js/frontend deployments.", estimatedSavingsPct: 10 },
    ],
  },

  // ─── Monitoring & Observability ───────────────────────────────────────────
  {
    id: "datadog",
    name: "Datadog",
    category: "monitoring",
    domains: ["api.datadoghq.com", "app.datadoghq.com", "datadoghq.com"],
    envVars: ["DD_API_KEY", "DD_APP_KEY", "DATADOG_API_KEY"],
    importHints: ["dd-trace", "datadog-lambda-js", "@datadog/browser-rum"],
    dependencyHints: ["dd-trace", "datadog-lambda-js", "@datadog/browser-rum", "@datadog/browser-logs"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Usage API available with API key." },
    cheaperAlternativeHeadline: "Datadog can get expensive at scale — alternatives exist.",
    alternatives: [
      { vendorId: "sentry", rationale: "Sentry for error tracking at a fraction of the cost.", estimatedSavingsPct: 60 },
      { vendorId: "axiom", rationale: "Axiom for logs at dramatically lower cost.", estimatedSavingsPct: 70 },
    ],
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "monitoring",
    domains: ["sentry.io", "o0.ingest.sentry.io"],
    envVars: ["SENTRY_DSN", "SENTRY_AUTH_TOKEN", "NEXT_PUBLIC_SENTRY_DSN"],
    importHints: ["@sentry/nextjs", "@sentry/node", "@sentry/react", "Sentry.init"],
    dependencyHints: ["@sentry/nextjs", "@sentry/node", "@sentry/react", "@sentry/browser"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Billing via Sentry API." },
    alternatives: [
      { vendorId: "datadog", rationale: "Datadog for full observability stack consolidation.", estimatedSavingsPct: 0 },
    ],
  },
  {
    id: "axiom",
    name: "Axiom",
    category: "monitoring",
    domains: ["api.axiom.co", "axiom.co", "cloud.axiom.co"],
    envVars: ["AXIOM_TOKEN", "AXIOM_DATASET", "NEXT_AXIOM_TOKEN"],
    importHints: ["@axiomhq/js", "next-axiom", "axiom"],
    dependencyHints: ["@axiomhq/js", "next-axiom"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Billing via dashboard." },
    alternatives: [],
  },

  // ─── Email ────────────────────────────────────────────────────────────────
  {
    id: "resend",
    name: "Resend",
    category: "email",
    domains: ["api.resend.com", "resend.com"],
    envVars: ["RESEND_API_KEY"],
    importHints: ["resend", "Resend", "from 'resend'"],
    dependencyHints: ["resend"],
    apiKeyPatterns: ["re_"],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Usage API available." },
    alternatives: [
      { vendorId: "sendgrid", rationale: "SendGrid for higher volume at negotiated rates.", estimatedSavingsPct: 10 },
    ],
  },

  // ─── Analytics ───────────────────────────────────────────────────────────
  {
    id: "mixpanel",
    name: "Mixpanel",
    category: "other",
    domains: ["api.mixpanel.com", "mixpanel.com"],
    envVars: ["MIXPANEL_TOKEN", "NEXT_PUBLIC_MIXPANEL_TOKEN"],
    importHints: ["mixpanel", "mixpanel-browser", "mixpanel-node"],
    dependencyHints: ["mixpanel", "mixpanel-browser"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Billing via dashboard." },
    alternatives: [
      { vendorId: "posthog", rationale: "PostHog open source — self-host for free.", estimatedSavingsPct: 80 },
    ],
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "other",
    domains: ["app.posthog.com", "eu.posthog.com", "posthog.com"],
    envVars: ["NEXT_PUBLIC_POSTHOG_KEY", "POSTHOG_API_KEY", "NEXT_PUBLIC_POSTHOG_HOST"],
    importHints: ["posthog-js", "posthog-node", "PostHog"],
    dependencyHints: ["posthog-js", "posthog-node"],
    apiKeyPatterns: ["phc_"],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Usage API available." },
    alternatives: [],
  },
  {
    id: "segment",
    name: "Segment",
    category: "other",
    domains: ["api.segment.io", "segment.io", "segment.com"],
    envVars: ["SEGMENT_WRITE_KEY", "NEXT_PUBLIC_SEGMENT_WRITE_KEY"],
    importHints: ["@segment/analytics-next", "analytics.js", "Analytics"],
    dependencyHints: ["@segment/analytics-next", "@segment/analytics-node"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Billing via Segment dashboard." },
    cheaperAlternativeHeadline: "Segment can be expensive — open source alternatives exist.",
    alternatives: [
      { vendorId: "posthog", rationale: "PostHog includes product analytics + session replay.", estimatedSavingsPct: 70 },
    ],
  },

  // ─── Search ──────────────────────────────────────────────────────────────
  {
    id: "algolia",
    name: "Algolia",
    category: "search",
    domains: ["algolia.net", "algolia.com", "algolianet.com"],
    envVars: ["ALGOLIA_APP_ID", "ALGOLIA_API_KEY", "ALGOLIA_SEARCH_API_KEY", "NEXT_PUBLIC_ALGOLIA_APP_ID"],
    importHints: ["algoliasearch", "instantsearch", "@algolia/client-search"],
    dependencyHints: ["algoliasearch", "instantsearch.js", "react-instantsearch"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Usage API available." },
    cheaperAlternativeHeadline: "Algolia gets expensive at scale.",
    alternatives: [
      { vendorId: "meilisearch", rationale: "Meilisearch open source — self-host for free.", estimatedSavingsPct: 80 },
    ],
  },
  {
    id: "meilisearch",
    name: "Meilisearch",
    category: "search",
    domains: ["cloud.meilisearch.com", "meilisearch.com"],
    envVars: ["MEILISEARCH_HOST", "MEILISEARCH_API_KEY", "MEILI_MASTER_KEY"],
    importHints: ["meilisearch", "MeiliSearch"],
    dependencyHints: ["meilisearch"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Self-hostable — billing only for Meilisearch Cloud." },
    alternatives: [],
  },

  // ─── Auth ─────────────────────────────────────────────────────────────────
  {
    id: "auth0",
    name: "Auth0",
    category: "auth",
    domains: ["auth0.com", "us.auth0.com", "eu.auth0.com"],
    envVars: ["AUTH0_SECRET", "AUTH0_BASE_URL", "AUTH0_ISSUER_BASE_URL", "AUTH0_CLIENT_ID", "AUTH0_CLIENT_SECRET"],
    importHints: ["@auth0/nextjs-auth0", "auth0", "Auth0Client"],
    dependencyHints: ["@auth0/nextjs-auth0", "@auth0/auth0-react", "@auth0/auth0-spa-js"],
    apiKeyPatterns: [],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: true, notes: "Management API available with client credentials." },
    cheaperAlternativeHeadline: "Auth0 pricing scales steeply with MAU.",
    alternatives: [
      { vendorId: "clerk", rationale: "Clerk is cheaper per MAU with better DX.", estimatedSavingsPct: 30 },
    ],
  },
  {
    id: "clerk",
    name: "Clerk",
    category: "auth",
    domains: ["clerk.com", "clerk.dev", "api.clerk.com"],
    envVars: ["CLERK_SECRET_KEY", "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", "CLERK_WEBHOOK_SECRET"],
    importHints: ["@clerk/nextjs", "@clerk/clerk-sdk-node", "clerkMiddleware"],
    dependencyHints: ["@clerk/nextjs", "@clerk/clerk-sdk-node"],
    apiKeyPatterns: ["sk_live_", "sk_test_"],
    pricingModel: "subscription",
    planDiscovery: { canOAuth: false, notes: "Billing API available." },
    alternatives: [
      { vendorId: "auth0", rationale: "Auth0 for enterprise SSO/compliance requirements.", estimatedSavingsPct: 0 },
    ],
  },

  // ─── Payments (additional) ────────────────────────────────────────────────
  {
    id: "paddle",
    name: "Paddle",
    category: "payments",
    domains: ["api.paddle.com", "checkout.paddle.com", "sandbox-api.paddle.com"],
    envVars: ["PADDLE_API_KEY", "PADDLE_WEBHOOK_SECRET", "NEXT_PUBLIC_PADDLE_CLIENT_TOKEN"],
    importHints: ["@paddle/paddle-js", "@paddle/paddle-node-sdk"],
    dependencyHints: ["@paddle/paddle-js", "@paddle/paddle-node-sdk"],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Billing via Paddle dashboard API." },
    alternatives: [
      { vendorId: "stripe", rationale: "Stripe for more control over payment flows.", estimatedSavingsPct: 0 },
    ],
  },
  {
    id: "lemon-squeezy",
    name: "Lemon Squeezy",
    category: "payments",
    domains: ["api.lemonsqueezy.com", "lemonsqueezy.com"],
    envVars: ["LEMONSQUEEZY_API_KEY", "LEMONSQUEEZY_WEBHOOK_SECRET", "LEMON_SQUEEZY_API_KEY"],
    importHints: ["@lemonsqueezy/lemonsqueezy.js"],
    dependencyHints: ["@lemonsqueezy/lemonsqueezy.js"],
    apiKeyPatterns: [],
    pricingModel: "per_request",
    planDiscovery: { canOAuth: false, notes: "Billing API available." },
    alternatives: [
      { vendorId: "stripe", rationale: "Stripe for more customization.", estimatedSavingsPct: 0 },
      { vendorId: "paddle", rationale: "Paddle for merchant of record model.", estimatedSavingsPct: 0 },
    ],
  },
];

export const VENDOR_MAP = Object.fromEntries(VENDORS.map((v) => [v.id, v]));
